---
- name: Déployer stack Docker Compose
  hosts: webservers
  become: yes

  vars:
    web_port: 8080
    compose_path: "/opt/stack"

  tasks:
    - name: Télécharger Docker Compose v2
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.24.1/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
    - name: Déployer index.html
      copy:
        dest: /opt/nginx-html/index.html
        content: |
          <h1>Welcome to Nginx via Docker Compose!</h1>
          <p>Deployment succeeded.</p>


    - name: Créer dossier stack
      file:
        path: "{{ compose_path }}"
        state: directory
        mode: "0755"

    - name: Déployer le fichier docker-compose.yml
      template:
        src: templates/docker-compose.yml.j2
        dest: "{{ compose_path }}/docker-compose.yml"
        
    - name: Déployer la stack via docker-compose CLI
      command: docker-compose -f {{ compose_path }}/docker-compose.yml up -d

